version: 2.1

orbs:
  moul: moul/build@1.10.0 # https://github.com/moul/build

workflows:
  main:
    jobs:
      - moul/golang-build:
          gopkg: moul.io/moulsay
      - moul/golang-build:
          gopkg: moul.io/moulsay
          tag: '1.11'
      - moul/docker-build
